platform :ios,'8.0'
pod "ParallaxBlur"
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "Parse"
pod "ParseUI"
pod "SDWebImage"
pod "MBProgressHUD"
pod "ParseFacebookUtilsV4"
pod "JDFPeekaboo"
pod "SSBouncyButton"
pod "MJRefresh"
pod "SCLAlertView-Objective-C"
pod "VBFPopFlatButton"
pod "DateTools"
pod "JTSImageViewController@bulusoy"

use_frameworks!
pod "TextFieldEffects"